/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElRouteImport } from './routes/el'
import { Route as EnRouteImport } from './routes/en'
import { Route as MyChartsRouteImport } from './routes/my-charts'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ElIndexRouteImport } from './routes/el.index'
import { Route as ElAnalitikaRouteImport } from './routes/el.analitika'
import { Route as ElEpikoinoniaRouteImport } from './routes/el.epikoinonia'
import { Route as ElOroiChrisisRouteImport } from './routes/el.oroi-chrisis'
import { Route as ElPolitikiAporritouRouteImport } from './routes/el.politiki-aporritou'
import { Route as ElPwsDiavazwGenethlioChartiRouteImport } from './routes/el.pws-diavazw-genethlio-charti'
import { Route as ElSchetikaRouteImport } from './routes/el.schetika'
import { Route as ElTiOroskopoEhoRouteImport } from './routes/el.ti-oroskopo-eho'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as EnAnalyticsRouteImport } from './routes/en.analytics'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnPrivacyRouteImport } from './routes/en.privacy'
import { Route as EnTermsRouteImport } from './routes/en.terms'
import { Route as ApiPublicBuildInfoRouteImport } from './routes/api/public/build-info'
import { Route as ApiPublicGenerateHoroscopesRouteImport } from './routes/api/public/generate-horoscopes'
import { Route as ApiPublicPublishInstagramRouteImport } from './routes/api/public/publish-instagram'
import { Route as ApiPublicPublishWatchRouteImport } from './routes/api/public/publish-watch'
import { Route as ApiPublicRenderStoriesRouteImport } from './routes/api/public/render-stories'
import { Route as ElZodiaIndexRouteImport } from './routes/el.zodia.index'
import { Route as EnZodiacIndexRouteImport } from './routes/en.zodiac.index'
import { Route as ElZodiaSignIndexRouteImport } from './routes/el.zodia.$sign.index'
import { Route as ElZodiaSignDateRouteImport } from './routes/el.zodia.$sign.$date'
import { Route as ElZodiaSignEtosRouteImport } from './routes/el.zodia.$sign.etos'
import { Route as ElZodiaSignMinasRouteImport } from './routes/el.zodia.$sign.minas'
import { Route as ElZodiaSignSimeraRouteImport } from './routes/el.zodia.$sign.simera'
import { Route as EnZodiacSignIndexRouteImport } from './routes/en.zodiac.$sign.index'
import { Route as EnZodiacSignDateRouteImport } from './routes/en.zodiac.$sign.$date'
import { Route as EnZodiacSignMonthRouteImport } from './routes/en.zodiac.$sign.month'
import { Route as EnZodiacSignTodayRouteImport } from './routes/en.zodiac.$sign.today'
import { Route as EnZodiacSignYearRouteImport } from './routes/en.zodiac.$sign.year'
import { Route as ApiPublicStoryImageDayFileRouteImport } from './routes/api/public/story-image.$day.$file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElRoute = ElRouteImport.update({
  id: '/el',
  path: '/el',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChartsRoute = MyChartsRouteImport.update({
  id: '/my-charts',
  path: '/my-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ElIndexRoute = ElIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElRoute,
} as any)
const ElAnalitikaRoute = ElAnalitikaRouteImport.update({
  id: '/analitika',
  path: '/analitika',
  getParentRoute: () => ElRoute,
} as any)
const ElEpikoinoniaRoute = ElEpikoinoniaRouteImport.update({
  id: '/epikoinonia',
  path: '/epikoinonia',
  getParentRoute: () => ElRoute,
} as any)
const ElOroiChrisisRoute = ElOroiChrisisRouteImport.update({
  id: '/oroi-chrisis',
  path: '/oroi-chrisis',
  getParentRoute: () => ElRoute,
} as any)
const ElPolitikiAporritouRoute = ElPolitikiAporritouRouteImport.update({
  id: '/politiki-aporritou',
  path: '/politiki-aporritou',
  getParentRoute: () => ElRoute,
} as any)
const ElPwsDiavazwGenethlioChartiRoute =
  ElPwsDiavazwGenethlioChartiRouteImport.update({
    id: '/pws-diavazw-genethlio-charti',
    path: '/pws-diavazw-genethlio-charti',
    getParentRoute: () => ElRoute,
  } as any)
const ElSchetikaRoute = ElSchetikaRouteImport.update({
  id: '/schetika',
  path: '/schetika',
  getParentRoute: () => ElRoute,
} as any)
const ElTiOroskopoEhoRoute = ElTiOroskopoEhoRouteImport.update({
  id: '/ti-oroskopo-eho',
  path: '/ti-oroskopo-eho',
  getParentRoute: () => ElRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const EnAnalyticsRoute = EnAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnPrivacyRoute = EnPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => EnRoute,
} as any)
const EnTermsRoute = EnTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => EnRoute,
} as any)
const ApiPublicBuildInfoRoute = ApiPublicBuildInfoRouteImport.update({
  id: '/api/public/build-info',
  path: '/api/public/build-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGenerateHoroscopesRoute =
  ApiPublicGenerateHoroscopesRouteImport.update({
    id: '/api/public/generate-horoscopes',
    path: '/api/public/generate-horoscopes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPublishInstagramRoute =
  ApiPublicPublishInstagramRouteImport.update({
    id: '/api/public/publish-instagram',
    path: '/api/public/publish-instagram',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPublishWatchRoute = ApiPublicPublishWatchRouteImport.update({
  id: '/api/public/publish-watch',
  path: '/api/public/publish-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRenderStoriesRoute = ApiPublicRenderStoriesRouteImport.update({
  id: '/api/public/render-stories',
  path: '/api/public/render-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const ElZodiaIndexRoute = ElZodiaIndexRouteImport.update({
  id: '/zodia/',
  path: '/zodia/',
  getParentRoute: () => ElRoute,
} as any)
const EnZodiacIndexRoute = EnZodiacIndexRouteImport.update({
  id: '/zodiac/',
  path: '/zodiac/',
  getParentRoute: () => EnRoute,
} as any)
const ElZodiaSignIndexRoute = ElZodiaSignIndexRouteImport.update({
  id: '/zodia/$sign/',
  path: '/zodia/$sign/',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignDateRoute = ElZodiaSignDateRouteImport.update({
  id: '/zodia/$sign/$date',
  path: '/zodia/$sign/$date',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignEtosRoute = ElZodiaSignEtosRouteImport.update({
  id: '/zodia/$sign/etos',
  path: '/zodia/$sign/etos',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignMinasRoute = ElZodiaSignMinasRouteImport.update({
  id: '/zodia/$sign/minas',
  path: '/zodia/$sign/minas',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignSimeraRoute = ElZodiaSignSimeraRouteImport.update({
  id: '/zodia/$sign/simera',
  path: '/zodia/$sign/simera',
  getParentRoute: () => ElRoute,
} as any)
const EnZodiacSignIndexRoute = EnZodiacSignIndexRouteImport.update({
  id: '/zodiac/$sign/',
  path: '/zodiac/$sign/',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignDateRoute = EnZodiacSignDateRouteImport.update({
  id: '/zodiac/$sign/$date',
  path: '/zodiac/$sign/$date',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignMonthRoute = EnZodiacSignMonthRouteImport.update({
  id: '/zodiac/$sign/month',
  path: '/zodiac/$sign/month',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignTodayRoute = EnZodiacSignTodayRouteImport.update({
  id: '/zodiac/$sign/today',
  path: '/zodiac/$sign/today',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignYearRoute = EnZodiacSignYearRouteImport.update({
  id: '/zodiac/$sign/year',
  path: '/zodiac/$sign/year',
  getParentRoute: () => EnRoute,
} as any)
const ApiPublicStoryImageDayFileRoute =
  ApiPublicStoryImageDayFileRouteImport.update({
    id: '/api/public/story-image/$day/$file',
    path: '/api/public/story-image/$day/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/el': typeof ElRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/my-charts': typeof MyChartsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/el/analitika': typeof ElAnalitikaRoute
  '/el/epikoinonia': typeof ElEpikoinoniaRoute
  '/el/oroi-chrisis': typeof ElOroiChrisisRoute
  '/el/politiki-aporritou': typeof ElPolitikiAporritouRoute
  '/el/pws-diavazw-genethlio-charti': typeof ElPwsDiavazwGenethlioChartiRoute
  '/el/schetika': typeof ElSchetikaRoute
  '/el/ti-oroskopo-eho': typeof ElTiOroskopoEhoRoute
  '/en/about': typeof EnAboutRoute
  '/en/analytics': typeof EnAnalyticsRoute
  '/en/contact': typeof EnContactRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/el/': typeof ElIndexRoute
  '/en/': typeof EnIndexRoute
  '/api/public/build-info': typeof ApiPublicBuildInfoRoute
  '/api/public/generate-horoscopes': typeof ApiPublicGenerateHoroscopesRoute
  '/api/public/publish-instagram': typeof ApiPublicPublishInstagramRoute
  '/api/public/publish-watch': typeof ApiPublicPublishWatchRoute
  '/api/public/render-stories': typeof ApiPublicRenderStoriesRoute
  '/el/zodia/': typeof ElZodiaIndexRoute
  '/en/zodiac/': typeof EnZodiacIndexRoute
  '/el/zodia/$sign/$date': typeof ElZodiaSignDateRoute
  '/el/zodia/$sign/etos': typeof ElZodiaSignEtosRoute
  '/el/zodia/$sign/minas': typeof ElZodiaSignMinasRoute
  '/el/zodia/$sign/simera': typeof ElZodiaSignSimeraRoute
  '/en/zodiac/$sign/$date': typeof EnZodiacSignDateRoute
  '/en/zodiac/$sign/month': typeof EnZodiacSignMonthRoute
  '/en/zodiac/$sign/today': typeof EnZodiacSignTodayRoute
  '/en/zodiac/$sign/year': typeof EnZodiacSignYearRoute
  '/el/zodia/$sign/': typeof ElZodiaSignIndexRoute
  '/en/zodiac/$sign/': typeof EnZodiacSignIndexRoute
  '/api/public/story-image/$day/$file': typeof ApiPublicStoryImageDayFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-charts': typeof MyChartsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/el/analitika': typeof ElAnalitikaRoute
  '/el/epikoinonia': typeof ElEpikoinoniaRoute
  '/el/oroi-chrisis': typeof ElOroiChrisisRoute
  '/el/politiki-aporritou': typeof ElPolitikiAporritouRoute
  '/el/pws-diavazw-genethlio-charti': typeof ElPwsDiavazwGenethlioChartiRoute
  '/el/schetika': typeof ElSchetikaRoute
  '/el/ti-oroskopo-eho': typeof ElTiOroskopoEhoRoute
  '/en/about': typeof EnAboutRoute
  '/en/analytics': typeof EnAnalyticsRoute
  '/en/contact': typeof EnContactRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/el': typeof ElIndexRoute
  '/en': typeof EnIndexRoute
  '/api/public/build-info': typeof ApiPublicBuildInfoRoute
  '/api/public/generate-horoscopes': typeof ApiPublicGenerateHoroscopesRoute
  '/api/public/publish-instagram': typeof ApiPublicPublishInstagramRoute
  '/api/public/publish-watch': typeof ApiPublicPublishWatchRoute
  '/api/public/render-stories': typeof ApiPublicRenderStoriesRoute
  '/el/zodia': typeof ElZodiaIndexRoute
  '/en/zodiac': typeof EnZodiacIndexRoute
  '/el/zodia/$sign/$date': typeof ElZodiaSignDateRoute
  '/el/zodia/$sign/etos': typeof ElZodiaSignEtosRoute
  '/el/zodia/$sign/minas': typeof ElZodiaSignMinasRoute
  '/el/zodia/$sign/simera': typeof ElZodiaSignSimeraRoute
  '/en/zodiac/$sign/$date': typeof EnZodiacSignDateRoute
  '/en/zodiac/$sign/month': typeof EnZodiacSignMonthRoute
  '/en/zodiac/$sign/today': typeof EnZodiacSignTodayRoute
  '/en/zodiac/$sign/year': typeof EnZodiacSignYearRoute
  '/el/zodia/$sign': typeof ElZodiaSignIndexRoute
  '/en/zodiac/$sign': typeof EnZodiacSignIndexRoute
  '/api/public/story-image/$day/$file': typeof ApiPublicStoryImageDayFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/el': typeof ElRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/my-charts': typeof MyChartsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/el/analitika': typeof ElAnalitikaRoute
  '/el/epikoinonia': typeof ElEpikoinoniaRoute
  '/el/oroi-chrisis': typeof ElOroiChrisisRoute
  '/el/politiki-aporritou': typeof ElPolitikiAporritouRoute
  '/el/pws-diavazw-genethlio-charti': typeof ElPwsDiavazwGenethlioChartiRoute
  '/el/schetika': typeof ElSchetikaRoute
  '/el/ti-oroskopo-eho': typeof ElTiOroskopoEhoRoute
  '/en/about': typeof EnAboutRoute
  '/en/analytics': typeof EnAnalyticsRoute
  '/en/contact': typeof EnContactRoute
  '/en/privacy': typeof EnPrivacyRoute
  '/en/terms': typeof EnTermsRoute
  '/el/': typeof ElIndexRoute
  '/en/': typeof EnIndexRoute
  '/api/public/build-info': typeof ApiPublicBuildInfoRoute
  '/api/public/generate-horoscopes': typeof ApiPublicGenerateHoroscopesRoute
  '/api/public/publish-instagram': typeof ApiPublicPublishInstagramRoute
  '/api/public/publish-watch': typeof ApiPublicPublishWatchRoute
  '/api/public/render-stories': typeof ApiPublicRenderStoriesRoute
  '/el/zodia/': typeof ElZodiaIndexRoute
  '/en/zodiac/': typeof EnZodiacIndexRoute
  '/el/zodia/$sign/$date': typeof ElZodiaSignDateRoute
  '/el/zodia/$sign/etos': typeof ElZodiaSignEtosRoute
  '/el/zodia/$sign/minas': typeof ElZodiaSignMinasRoute
  '/el/zodia/$sign/simera': typeof ElZodiaSignSimeraRoute
  '/en/zodiac/$sign/$date': typeof EnZodiacSignDateRoute
  '/en/zodiac/$sign/month': typeof EnZodiacSignMonthRoute
  '/en/zodiac/$sign/today': typeof EnZodiacSignTodayRoute
  '/en/zodiac/$sign/year': typeof EnZodiacSignYearRoute
  '/el/zodia/$sign/': typeof ElZodiaSignIndexRoute
  '/en/zodiac/$sign/': typeof EnZodiacSignIndexRoute
  '/api/public/story-image/$day/$file': typeof ApiPublicStoryImageDayFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/el'
    | '/en'
    | '/my-charts'
    | '/sitemap.xml'
    | '/el/analitika'
    | '/el/epikoinonia'
    | '/el/oroi-chrisis'
    | '/el/politiki-aporritou'
    | '/el/pws-diavazw-genethlio-charti'
    | '/el/schetika'
    | '/el/ti-oroskopo-eho'
    | '/en/about'
    | '/en/analytics'
    | '/en/contact'
    | '/en/privacy'
    | '/en/terms'
    | '/el/'
    | '/en/'
    | '/api/public/build-info'
    | '/api/public/generate-horoscopes'
    | '/api/public/publish-instagram'
    | '/api/public/publish-watch'
    | '/api/public/render-stories'
    | '/el/zodia/'
    | '/en/zodiac/'
    | '/el/zodia/$sign/$date'
    | '/el/zodia/$sign/etos'
    | '/el/zodia/$sign/minas'
    | '/el/zodia/$sign/simera'
    | '/en/zodiac/$sign/$date'
    | '/en/zodiac/$sign/month'
    | '/en/zodiac/$sign/today'
    | '/en/zodiac/$sign/year'
    | '/el/zodia/$sign/'
    | '/en/zodiac/$sign/'
    | '/api/public/story-image/$day/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-charts'
    | '/sitemap.xml'
    | '/el/analitika'
    | '/el/epikoinonia'
    | '/el/oroi-chrisis'
    | '/el/politiki-aporritou'
    | '/el/pws-diavazw-genethlio-charti'
    | '/el/schetika'
    | '/el/ti-oroskopo-eho'
    | '/en/about'
    | '/en/analytics'
    | '/en/contact'
    | '/en/privacy'
    | '/en/terms'
    | '/el'
    | '/en'
    | '/api/public/build-info'
    | '/api/public/generate-horoscopes'
    | '/api/public/publish-instagram'
    | '/api/public/publish-watch'
    | '/api/public/render-stories'
    | '/el/zodia'
    | '/en/zodiac'
    | '/el/zodia/$sign/$date'
    | '/el/zodia/$sign/etos'
    | '/el/zodia/$sign/minas'
    | '/el/zodia/$sign/simera'
    | '/en/zodiac/$sign/$date'
    | '/en/zodiac/$sign/month'
    | '/en/zodiac/$sign/today'
    | '/en/zodiac/$sign/year'
    | '/el/zodia/$sign'
    | '/en/zodiac/$sign'
    | '/api/public/story-image/$day/$file'
  id:
    | '__root__'
    | '/'
    | '/el'
    | '/en'
    | '/my-charts'
    | '/sitemap.xml'
    | '/el/analitika'
    | '/el/epikoinonia'
    | '/el/oroi-chrisis'
    | '/el/politiki-aporritou'
    | '/el/pws-diavazw-genethlio-charti'
    | '/el/schetika'
    | '/el/ti-oroskopo-eho'
    | '/en/about'
    | '/en/analytics'
    | '/en/contact'
    | '/en/privacy'
    | '/en/terms'
    | '/el/'
    | '/en/'
    | '/api/public/build-info'
    | '/api/public/generate-horoscopes'
    | '/api/public/publish-instagram'
    | '/api/public/publish-watch'
    | '/api/public/render-stories'
    | '/el/zodia/'
    | '/en/zodiac/'
    | '/el/zodia/$sign/$date'
    | '/el/zodia/$sign/etos'
    | '/el/zodia/$sign/minas'
    | '/el/zodia/$sign/simera'
    | '/en/zodiac/$sign/$date'
    | '/en/zodiac/$sign/month'
    | '/en/zodiac/$sign/today'
    | '/en/zodiac/$sign/year'
    | '/el/zodia/$sign/'
    | '/en/zodiac/$sign/'
    | '/api/public/story-image/$day/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElRoute: typeof ElRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  MyChartsRoute: typeof MyChartsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBuildInfoRoute: typeof ApiPublicBuildInfoRoute
  ApiPublicGenerateHoroscopesRoute: typeof ApiPublicGenerateHoroscopesRoute
  ApiPublicPublishInstagramRoute: typeof ApiPublicPublishInstagramRoute
  ApiPublicPublishWatchRoute: typeof ApiPublicPublishWatchRoute
  ApiPublicRenderStoriesRoute: typeof ApiPublicRenderStoriesRoute
  ApiPublicStoryImageDayFileRoute: typeof ApiPublicStoryImageDayFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el': {
      id: '/el'
      path: '/el'
      fullPath: '/el'
      preLoaderRoute: typeof ElRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-charts': {
      id: '/my-charts'
      path: '/my-charts'
      fullPath: '/my-charts'
      preLoaderRoute: typeof MyChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/': {
      id: '/el/'
      path: '/'
      fullPath: '/el/'
      preLoaderRoute: typeof ElIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/analitika': {
      id: '/el/analitika'
      path: '/analitika'
      fullPath: '/el/analitika'
      preLoaderRoute: typeof ElAnalitikaRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/epikoinonia': {
      id: '/el/epikoinonia'
      path: '/epikoinonia'
      fullPath: '/el/epikoinonia'
      preLoaderRoute: typeof ElEpikoinoniaRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/oroi-chrisis': {
      id: '/el/oroi-chrisis'
      path: '/oroi-chrisis'
      fullPath: '/el/oroi-chrisis'
      preLoaderRoute: typeof ElOroiChrisisRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/politiki-aporritou': {
      id: '/el/politiki-aporritou'
      path: '/politiki-aporritou'
      fullPath: '/el/politiki-aporritou'
      preLoaderRoute: typeof ElPolitikiAporritouRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/pws-diavazw-genethlio-charti': {
      id: '/el/pws-diavazw-genethlio-charti'
      path: '/pws-diavazw-genethlio-charti'
      fullPath: '/el/pws-diavazw-genethlio-charti'
      preLoaderRoute: typeof ElPwsDiavazwGenethlioChartiRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/schetika': {
      id: '/el/schetika'
      path: '/schetika'
      fullPath: '/el/schetika'
      preLoaderRoute: typeof ElSchetikaRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/ti-oroskopo-eho': {
      id: '/el/ti-oroskopo-eho'
      path: '/ti-oroskopo-eho'
      fullPath: '/el/ti-oroskopo-eho'
      preLoaderRoute: typeof ElTiOroskopoEhoRouteImport
      parentRoute: typeof ElRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/analytics': {
      id: '/en/analytics'
      path: '/analytics'
      fullPath: '/en/analytics'
      preLoaderRoute: typeof EnAnalyticsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/privacy': {
      id: '/en/privacy'
      path: '/privacy'
      fullPath: '/en/privacy'
      preLoaderRoute: typeof EnPrivacyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/terms': {
      id: '/en/terms'
      path: '/terms'
      fullPath: '/en/terms'
      preLoaderRoute: typeof EnTermsRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/public/build-info': {
      id: '/api/public/build-info'
      path: '/api/public/build-info'
      fullPath: '/api/public/build-info'
      preLoaderRoute: typeof ApiPublicBuildInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/generate-horoscopes': {
      id: '/api/public/generate-horoscopes'
      path: '/api/public/generate-horoscopes'
      fullPath: '/api/public/generate-horoscopes'
      preLoaderRoute: typeof ApiPublicGenerateHoroscopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publish-instagram': {
      id: '/api/public/publish-instagram'
      path: '/api/public/publish-instagram'
      fullPath: '/api/public/publish-instagram'
      preLoaderRoute: typeof ApiPublicPublishInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publish-watch': {
      id: '/api/public/publish-watch'
      path: '/api/public/publish-watch'
      fullPath: '/api/public/publish-watch'
      preLoaderRoute: typeof ApiPublicPublishWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/render-stories': {
      id: '/api/public/render-stories'
      path: '/api/public/render-stories'
      fullPath: '/api/public/render-stories'
      preLoaderRoute: typeof ApiPublicRenderStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/zodia/': {
      id: '/el/zodia/'
      path: '/zodia'
      fullPath: '/el/zodia/'
      preLoaderRoute: typeof ElZodiaIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/en/zodiac/': {
      id: '/en/zodiac/'
      path: '/zodiac'
      fullPath: '/en/zodiac/'
      preLoaderRoute: typeof EnZodiacIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/el/zodia/$sign/': {
      id: '/el/zodia/$sign/'
      path: '/zodia/$sign'
      fullPath: '/el/zodia/$sign/'
      preLoaderRoute: typeof ElZodiaSignIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/$date': {
      id: '/el/zodia/$sign/$date'
      path: '/zodia/$sign/$date'
      fullPath: '/el/zodia/$sign/$date'
      preLoaderRoute: typeof ElZodiaSignDateRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/etos': {
      id: '/el/zodia/$sign/etos'
      path: '/zodia/$sign/etos'
      fullPath: '/el/zodia/$sign/etos'
      preLoaderRoute: typeof ElZodiaSignEtosRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/minas': {
      id: '/el/zodia/$sign/minas'
      path: '/zodia/$sign/minas'
      fullPath: '/el/zodia/$sign/minas'
      preLoaderRoute: typeof ElZodiaSignMinasRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/simera': {
      id: '/el/zodia/$sign/simera'
      path: '/zodia/$sign/simera'
      fullPath: '/el/zodia/$sign/simera'
      preLoaderRoute: typeof ElZodiaSignSimeraRouteImport
      parentRoute: typeof ElRoute
    }
    '/en/zodiac/$sign/': {
      id: '/en/zodiac/$sign/'
      path: '/zodiac/$sign'
      fullPath: '/en/zodiac/$sign/'
      preLoaderRoute: typeof EnZodiacSignIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/$date': {
      id: '/en/zodiac/$sign/$date'
      path: '/zodiac/$sign/$date'
      fullPath: '/en/zodiac/$sign/$date'
      preLoaderRoute: typeof EnZodiacSignDateRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/month': {
      id: '/en/zodiac/$sign/month'
      path: '/zodiac/$sign/month'
      fullPath: '/en/zodiac/$sign/month'
      preLoaderRoute: typeof EnZodiacSignMonthRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/today': {
      id: '/en/zodiac/$sign/today'
      path: '/zodiac/$sign/today'
      fullPath: '/en/zodiac/$sign/today'
      preLoaderRoute: typeof EnZodiacSignTodayRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/year': {
      id: '/en/zodiac/$sign/year'
      path: '/zodiac/$sign/year'
      fullPath: '/en/zodiac/$sign/year'
      preLoaderRoute: typeof EnZodiacSignYearRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/public/story-image/$day/$file': {
      id: '/api/public/story-image/$day/$file'
      path: '/api/public/story-image/$day/$file'
      fullPath: '/api/public/story-image/$day/$file'
      preLoaderRoute: typeof ApiPublicStoryImageDayFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElRouteChildren {
  ElAnalitikaRoute: typeof ElAnalitikaRoute
  ElEpikoinoniaRoute: typeof ElEpikoinoniaRoute
  ElOroiChrisisRoute: typeof ElOroiChrisisRoute
  ElPolitikiAporritouRoute: typeof ElPolitikiAporritouRoute
  ElPwsDiavazwGenethlioChartiRoute: typeof ElPwsDiavazwGenethlioChartiRoute
  ElSchetikaRoute: typeof ElSchetikaRoute
  ElTiOroskopoEhoRoute: typeof ElTiOroskopoEhoRoute
  ElIndexRoute: typeof ElIndexRoute
  ElZodiaIndexRoute: typeof ElZodiaIndexRoute
  ElZodiaSignDateRoute: typeof ElZodiaSignDateRoute
  ElZodiaSignEtosRoute: typeof ElZodiaSignEtosRoute
  ElZodiaSignMinasRoute: typeof ElZodiaSignMinasRoute
  ElZodiaSignSimeraRoute: typeof ElZodiaSignSimeraRoute
  ElZodiaSignIndexRoute: typeof ElZodiaSignIndexRoute
}

const ElRouteChildren: ElRouteChildren = {
  ElAnalitikaRoute: ElAnalitikaRoute,
  ElEpikoinoniaRoute: ElEpikoinoniaRoute,
  ElOroiChrisisRoute: ElOroiChrisisRoute,
  ElPolitikiAporritouRoute: ElPolitikiAporritouRoute,
  ElPwsDiavazwGenethlioChartiRoute: ElPwsDiavazwGenethlioChartiRoute,
  ElSchetikaRoute: ElSchetikaRoute,
  ElTiOroskopoEhoRoute: ElTiOroskopoEhoRoute,
  ElIndexRoute: ElIndexRoute,
  ElZodiaIndexRoute: ElZodiaIndexRoute,
  ElZodiaSignDateRoute: ElZodiaSignDateRoute,
  ElZodiaSignEtosRoute: ElZodiaSignEtosRoute,
  ElZodiaSignMinasRoute: ElZodiaSignMinasRoute,
  ElZodiaSignSimeraRoute: ElZodiaSignSimeraRoute,
  ElZodiaSignIndexRoute: ElZodiaSignIndexRoute,
}

const ElRouteWithChildren = ElRoute._addFileChildren(ElRouteChildren)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnAnalyticsRoute: typeof EnAnalyticsRoute
  EnContactRoute: typeof EnContactRoute
  EnPrivacyRoute: typeof EnPrivacyRoute
  EnTermsRoute: typeof EnTermsRoute
  EnIndexRoute: typeof EnIndexRoute
  EnZodiacIndexRoute: typeof EnZodiacIndexRoute
  EnZodiacSignDateRoute: typeof EnZodiacSignDateRoute
  EnZodiacSignMonthRoute: typeof EnZodiacSignMonthRoute
  EnZodiacSignTodayRoute: typeof EnZodiacSignTodayRoute
  EnZodiacSignYearRoute: typeof EnZodiacSignYearRoute
  EnZodiacSignIndexRoute: typeof EnZodiacSignIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnAnalyticsRoute: EnAnalyticsRoute,
  EnContactRoute: EnContactRoute,
  EnPrivacyRoute: EnPrivacyRoute,
  EnTermsRoute: EnTermsRoute,
  EnIndexRoute: EnIndexRoute,
  EnZodiacIndexRoute: EnZodiacIndexRoute,
  EnZodiacSignDateRoute: EnZodiacSignDateRoute,
  EnZodiacSignMonthRoute: EnZodiacSignMonthRoute,
  EnZodiacSignTodayRoute: EnZodiacSignTodayRoute,
  EnZodiacSignYearRoute: EnZodiacSignYearRoute,
  EnZodiacSignIndexRoute: EnZodiacSignIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElRoute: ElRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  MyChartsRoute: MyChartsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBuildInfoRoute: ApiPublicBuildInfoRoute,
  ApiPublicGenerateHoroscopesRoute: ApiPublicGenerateHoroscopesRoute,
  ApiPublicPublishInstagramRoute: ApiPublicPublishInstagramRoute,
  ApiPublicPublishWatchRoute: ApiPublicPublishWatchRoute,
  ApiPublicRenderStoriesRoute: ApiPublicRenderStoriesRoute,
  ApiPublicStoryImageDayFileRoute: ApiPublicStoryImageDayFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
