/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElRouteImport } from './routes/el'
import { Route as EnRouteImport } from './routes/en'
import { Route as MyChartsRouteImport } from './routes/my-charts'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ElIndexRouteImport } from './routes/el.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ApiPublicBuildInfoRouteImport } from './routes/api/public/build-info'
import { Route as ApiPublicPublishWatchRouteImport } from './routes/api/public/publish-watch'
import { Route as ElZodiaIndexRouteImport } from './routes/el.zodia.index'
import { Route as EnZodiacIndexRouteImport } from './routes/en.zodiac.index'
import { Route as ElZodiaSignIndexRouteImport } from './routes/el.zodia.$sign.index'
import { Route as ElZodiaSignDateRouteImport } from './routes/el.zodia.$sign.$date'
import { Route as ElZodiaSignEtosRouteImport } from './routes/el.zodia.$sign.etos'
import { Route as ElZodiaSignMinasRouteImport } from './routes/el.zodia.$sign.minas'
import { Route as ElZodiaSignSimeraRouteImport } from './routes/el.zodia.$sign.simera'
import { Route as EnZodiacSignIndexRouteImport } from './routes/en.zodiac.$sign.index'
import { Route as EnZodiacSignDateRouteImport } from './routes/en.zodiac.$sign.$date'
import { Route as EnZodiacSignMonthRouteImport } from './routes/en.zodiac.$sign.month'
import { Route as EnZodiacSignTodayRouteImport } from './routes/en.zodiac.$sign.today'
import { Route as EnZodiacSignYearRouteImport } from './routes/en.zodiac.$sign.year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElRoute = ElRouteImport.update({
  id: '/el',
  path: '/el',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChartsRoute = MyChartsRouteImport.update({
  id: '/my-charts',
  path: '/my-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ElIndexRoute = ElIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const ApiPublicBuildInfoRoute = ApiPublicBuildInfoRouteImport.update({
  id: '/api/public/build-info',
  path: '/api/public/build-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPublishWatchRoute = ApiPublicPublishWatchRouteImport.update({
  id: '/api/public/publish-watch',
  path: '/api/public/publish-watch',
  getParentRoute: () => rootRouteImport,
} as any)
const ElZodiaIndexRoute = ElZodiaIndexRouteImport.update({
  id: '/zodia/',
  path: '/zodia/',
  getParentRoute: () => ElRoute,
} as any)
const EnZodiacIndexRoute = EnZodiacIndexRouteImport.update({
  id: '/zodiac/',
  path: '/zodiac/',
  getParentRoute: () => EnRoute,
} as any)
const ElZodiaSignIndexRoute = ElZodiaSignIndexRouteImport.update({
  id: '/zodia/$sign/',
  path: '/zodia/$sign/',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignDateRoute = ElZodiaSignDateRouteImport.update({
  id: '/zodia/$sign/$date',
  path: '/zodia/$sign/$date',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignEtosRoute = ElZodiaSignEtosRouteImport.update({
  id: '/zodia/$sign/etos',
  path: '/zodia/$sign/etos',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignMinasRoute = ElZodiaSignMinasRouteImport.update({
  id: '/zodia/$sign/minas',
  path: '/zodia/$sign/minas',
  getParentRoute: () => ElRoute,
} as any)
const ElZodiaSignSimeraRoute = ElZodiaSignSimeraRouteImport.update({
  id: '/zodia/$sign/simera',
  path: '/zodia/$sign/simera',
  getParentRoute: () => ElRoute,
} as any)
const EnZodiacSignIndexRoute = EnZodiacSignIndexRouteImport.update({
  id: '/zodiac/$sign/',
  path: '/zodiac/$sign/',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignDateRoute = EnZodiacSignDateRouteImport.update({
  id: '/zodiac/$sign/$date',
  path: '/zodiac/$sign/$date',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignMonthRoute = EnZodiacSignMonthRouteImport.update({
  id: '/zodiac/$sign/month',
  path: '/zodiac/$sign/month',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignTodayRoute = EnZodiacSignTodayRouteImport.update({
  id: '/zodiac/$sign/today',
  path: '/zodiac/$sign/today',
  getParentRoute: () => EnRoute,
} as any)
const EnZodiacSignYearRoute = EnZodiacSignYearRouteImport.update({
  id: '/zodiac/$sign/year',
  path: '/zodiac/$sign/year',
  getParentRoute: () => EnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/el': typeof ElRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/my-charts': typeof MyChartsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/el/': typeof ElIndexRoute
  '/en/': typeof EnIndexRoute
  '/api/public/build-info': typeof ApiPublicBuildInfoRoute
  '/api/public/publish-watch': typeof ApiPublicPublishWatchRoute
  '/el/zodia/': typeof ElZodiaIndexRoute
  '/en/zodiac/': typeof EnZodiacIndexRoute
  '/el/zodia/$sign/$date': typeof ElZodiaSignDateRoute
  '/el/zodia/$sign/etos': typeof ElZodiaSignEtosRoute
  '/el/zodia/$sign/minas': typeof ElZodiaSignMinasRoute
  '/el/zodia/$sign/simera': typeof ElZodiaSignSimeraRoute
  '/en/zodiac/$sign/$date': typeof EnZodiacSignDateRoute
  '/en/zodiac/$sign/month': typeof EnZodiacSignMonthRoute
  '/en/zodiac/$sign/today': typeof EnZodiacSignTodayRoute
  '/en/zodiac/$sign/year': typeof EnZodiacSignYearRoute
  '/el/zodia/$sign/': typeof ElZodiaSignIndexRoute
  '/en/zodiac/$sign/': typeof EnZodiacSignIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-charts': typeof MyChartsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/el': typeof ElIndexRoute
  '/en': typeof EnIndexRoute
  '/api/public/build-info': typeof ApiPublicBuildInfoRoute
  '/api/public/publish-watch': typeof ApiPublicPublishWatchRoute
  '/el/zodia': typeof ElZodiaIndexRoute
  '/en/zodiac': typeof EnZodiacIndexRoute
  '/el/zodia/$sign/$date': typeof ElZodiaSignDateRoute
  '/el/zodia/$sign/etos': typeof ElZodiaSignEtosRoute
  '/el/zodia/$sign/minas': typeof ElZodiaSignMinasRoute
  '/el/zodia/$sign/simera': typeof ElZodiaSignSimeraRoute
  '/en/zodiac/$sign/$date': typeof EnZodiacSignDateRoute
  '/en/zodiac/$sign/month': typeof EnZodiacSignMonthRoute
  '/en/zodiac/$sign/today': typeof EnZodiacSignTodayRoute
  '/en/zodiac/$sign/year': typeof EnZodiacSignYearRoute
  '/el/zodia/$sign': typeof ElZodiaSignIndexRoute
  '/en/zodiac/$sign': typeof EnZodiacSignIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/el': typeof ElRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/my-charts': typeof MyChartsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/el/': typeof ElIndexRoute
  '/en/': typeof EnIndexRoute
  '/api/public/build-info': typeof ApiPublicBuildInfoRoute
  '/api/public/publish-watch': typeof ApiPublicPublishWatchRoute
  '/el/zodia/': typeof ElZodiaIndexRoute
  '/en/zodiac/': typeof EnZodiacIndexRoute
  '/el/zodia/$sign/$date': typeof ElZodiaSignDateRoute
  '/el/zodia/$sign/etos': typeof ElZodiaSignEtosRoute
  '/el/zodia/$sign/minas': typeof ElZodiaSignMinasRoute
  '/el/zodia/$sign/simera': typeof ElZodiaSignSimeraRoute
  '/en/zodiac/$sign/$date': typeof EnZodiacSignDateRoute
  '/en/zodiac/$sign/month': typeof EnZodiacSignMonthRoute
  '/en/zodiac/$sign/today': typeof EnZodiacSignTodayRoute
  '/en/zodiac/$sign/year': typeof EnZodiacSignYearRoute
  '/el/zodia/$sign/': typeof ElZodiaSignIndexRoute
  '/en/zodiac/$sign/': typeof EnZodiacSignIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/el'
    | '/en'
    | '/my-charts'
    | '/sitemap.xml'
    | '/el/'
    | '/en/'
    | '/api/public/build-info'
    | '/api/public/publish-watch'
    | '/el/zodia/'
    | '/en/zodiac/'
    | '/el/zodia/$sign/$date'
    | '/el/zodia/$sign/etos'
    | '/el/zodia/$sign/minas'
    | '/el/zodia/$sign/simera'
    | '/en/zodiac/$sign/$date'
    | '/en/zodiac/$sign/month'
    | '/en/zodiac/$sign/today'
    | '/en/zodiac/$sign/year'
    | '/el/zodia/$sign/'
    | '/en/zodiac/$sign/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-charts'
    | '/sitemap.xml'
    | '/el'
    | '/en'
    | '/api/public/build-info'
    | '/api/public/publish-watch'
    | '/el/zodia'
    | '/en/zodiac'
    | '/el/zodia/$sign/$date'
    | '/el/zodia/$sign/etos'
    | '/el/zodia/$sign/minas'
    | '/el/zodia/$sign/simera'
    | '/en/zodiac/$sign/$date'
    | '/en/zodiac/$sign/month'
    | '/en/zodiac/$sign/today'
    | '/en/zodiac/$sign/year'
    | '/el/zodia/$sign'
    | '/en/zodiac/$sign'
  id:
    | '__root__'
    | '/'
    | '/el'
    | '/en'
    | '/my-charts'
    | '/sitemap.xml'
    | '/el/'
    | '/en/'
    | '/api/public/build-info'
    | '/api/public/publish-watch'
    | '/el/zodia/'
    | '/en/zodiac/'
    | '/el/zodia/$sign/$date'
    | '/el/zodia/$sign/etos'
    | '/el/zodia/$sign/minas'
    | '/el/zodia/$sign/simera'
    | '/en/zodiac/$sign/$date'
    | '/en/zodiac/$sign/month'
    | '/en/zodiac/$sign/today'
    | '/en/zodiac/$sign/year'
    | '/el/zodia/$sign/'
    | '/en/zodiac/$sign/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ElRoute: typeof ElRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  MyChartsRoute: typeof MyChartsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicBuildInfoRoute: typeof ApiPublicBuildInfoRoute
  ApiPublicPublishWatchRoute: typeof ApiPublicPublishWatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el': {
      id: '/el'
      path: '/el'
      fullPath: '/el'
      preLoaderRoute: typeof ElRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-charts': {
      id: '/my-charts'
      path: '/my-charts'
      fullPath: '/my-charts'
      preLoaderRoute: typeof MyChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/': {
      id: '/el/'
      path: '/'
      fullPath: '/el/'
      preLoaderRoute: typeof ElIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/api/public/build-info': {
      id: '/api/public/build-info'
      path: '/api/public/build-info'
      fullPath: '/api/public/build-info'
      preLoaderRoute: typeof ApiPublicBuildInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/publish-watch': {
      id: '/api/public/publish-watch'
      path: '/api/public/publish-watch'
      fullPath: '/api/public/publish-watch'
      preLoaderRoute: typeof ApiPublicPublishWatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/zodia/': {
      id: '/el/zodia/'
      path: '/zodia'
      fullPath: '/el/zodia/'
      preLoaderRoute: typeof ElZodiaIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/en/zodiac/': {
      id: '/en/zodiac/'
      path: '/zodiac'
      fullPath: '/en/zodiac/'
      preLoaderRoute: typeof EnZodiacIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/el/zodia/$sign/': {
      id: '/el/zodia/$sign/'
      path: '/zodia/$sign'
      fullPath: '/el/zodia/$sign/'
      preLoaderRoute: typeof ElZodiaSignIndexRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/$date': {
      id: '/el/zodia/$sign/$date'
      path: '/zodia/$sign/$date'
      fullPath: '/el/zodia/$sign/$date'
      preLoaderRoute: typeof ElZodiaSignDateRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/etos': {
      id: '/el/zodia/$sign/etos'
      path: '/zodia/$sign/etos'
      fullPath: '/el/zodia/$sign/etos'
      preLoaderRoute: typeof ElZodiaSignEtosRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/minas': {
      id: '/el/zodia/$sign/minas'
      path: '/zodia/$sign/minas'
      fullPath: '/el/zodia/$sign/minas'
      preLoaderRoute: typeof ElZodiaSignMinasRouteImport
      parentRoute: typeof ElRoute
    }
    '/el/zodia/$sign/simera': {
      id: '/el/zodia/$sign/simera'
      path: '/zodia/$sign/simera'
      fullPath: '/el/zodia/$sign/simera'
      preLoaderRoute: typeof ElZodiaSignSimeraRouteImport
      parentRoute: typeof ElRoute
    }
    '/en/zodiac/$sign/': {
      id: '/en/zodiac/$sign/'
      path: '/zodiac/$sign'
      fullPath: '/en/zodiac/$sign/'
      preLoaderRoute: typeof EnZodiacSignIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/$date': {
      id: '/en/zodiac/$sign/$date'
      path: '/zodiac/$sign/$date'
      fullPath: '/en/zodiac/$sign/$date'
      preLoaderRoute: typeof EnZodiacSignDateRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/month': {
      id: '/en/zodiac/$sign/month'
      path: '/zodiac/$sign/month'
      fullPath: '/en/zodiac/$sign/month'
      preLoaderRoute: typeof EnZodiacSignMonthRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/today': {
      id: '/en/zodiac/$sign/today'
      path: '/zodiac/$sign/today'
      fullPath: '/en/zodiac/$sign/today'
      preLoaderRoute: typeof EnZodiacSignTodayRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/zodiac/$sign/year': {
      id: '/en/zodiac/$sign/year'
      path: '/zodiac/$sign/year'
      fullPath: '/en/zodiac/$sign/year'
      preLoaderRoute: typeof EnZodiacSignYearRouteImport
      parentRoute: typeof EnRoute
    }
  }
}

interface ElRouteChildren {
  ElIndexRoute: typeof ElIndexRoute
  ElZodiaIndexRoute: typeof ElZodiaIndexRoute
  ElZodiaSignDateRoute: typeof ElZodiaSignDateRoute
  ElZodiaSignEtosRoute: typeof ElZodiaSignEtosRoute
  ElZodiaSignMinasRoute: typeof ElZodiaSignMinasRoute
  ElZodiaSignSimeraRoute: typeof ElZodiaSignSimeraRoute
  ElZodiaSignIndexRoute: typeof ElZodiaSignIndexRoute
}

const ElRouteChildren: ElRouteChildren = {
  ElIndexRoute: ElIndexRoute,
  ElZodiaIndexRoute: ElZodiaIndexRoute,
  ElZodiaSignDateRoute: ElZodiaSignDateRoute,
  ElZodiaSignEtosRoute: ElZodiaSignEtosRoute,
  ElZodiaSignMinasRoute: ElZodiaSignMinasRoute,
  ElZodiaSignSimeraRoute: ElZodiaSignSimeraRoute,
  ElZodiaSignIndexRoute: ElZodiaSignIndexRoute,
}

const ElRouteWithChildren = ElRoute._addFileChildren(ElRouteChildren)

interface EnRouteChildren {
  EnIndexRoute: typeof EnIndexRoute
  EnZodiacIndexRoute: typeof EnZodiacIndexRoute
  EnZodiacSignDateRoute: typeof EnZodiacSignDateRoute
  EnZodiacSignMonthRoute: typeof EnZodiacSignMonthRoute
  EnZodiacSignTodayRoute: typeof EnZodiacSignTodayRoute
  EnZodiacSignYearRoute: typeof EnZodiacSignYearRoute
  EnZodiacSignIndexRoute: typeof EnZodiacSignIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnIndexRoute: EnIndexRoute,
  EnZodiacIndexRoute: EnZodiacIndexRoute,
  EnZodiacSignDateRoute: EnZodiacSignDateRoute,
  EnZodiacSignMonthRoute: EnZodiacSignMonthRoute,
  EnZodiacSignTodayRoute: EnZodiacSignTodayRoute,
  EnZodiacSignYearRoute: EnZodiacSignYearRoute,
  EnZodiacSignIndexRoute: EnZodiacSignIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ElRoute: ElRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  MyChartsRoute: MyChartsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicBuildInfoRoute: ApiPublicBuildInfoRoute,
  ApiPublicPublishWatchRoute: ApiPublicPublishWatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
